# Generated by Django 5.2.11 on 2026-02-27 19:16

import django.db.models.deletion
import django.utils.timezone
import engagement.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='CCTV Recording', max_length=255)),
                ('video_file', models.FileField(upload_to=engagement.models.video_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('total_frames', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.RemoveField(
            model_name='engagementrecord',
            name='attention_score',
        ),
        migrations.RemoveField(
            model_name='engagementrecord',
            name='emotion',
        ),
        migrations.RemoveField(
            model_name='engagementrecord',
            name='student',
        ),
        migrations.AddField(
            model_name='engagementrecord',
            name='attentive_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='engagementrecord',
            name='distracted_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='engagementrecord',
            name='engagement_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='engagementrecord',
            name='frame_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engagementrecord',
            name='neutral_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='engagementrecord',
            name='processing_time',
            field=models.FloatField(blank=True, help_text='Time taken to process this frame in seconds', null=True),
        ),
        migrations.AddField(
            model_name='engagementrecord',
            name='sleepy_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='engagementrecord',
            name='total_students',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='engagementrecord',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='engagementrecord',
            name='video_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engagement_records', to='engagement.videoupload'),
        ),
    ]
